-- MySQL Script generated by MySQL Workbench
-- Wed Aug 24 17:38:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crud_prueba_tecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crud_prueba_tecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crud_prueba_tecnica` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `crud_prueba_tecnica` ;

-- -----------------------------------------------------
-- Table `crud_prueba_tecnica`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_prueba_tecnica`.`areas` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_prueba_tecnica`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_prueba_tecnica`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `boletin` INT(11) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `areas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleados_areas1_idx` (`areas_id` ASC),
  CONSTRAINT `fk_empleados_areas1`
    FOREIGN KEY (`areas_id`)
    REFERENCES `crud_prueba_tecnica`.`areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_prueba_tecnica`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_prueba_tecnica`.`roles` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crud_prueba_tecnica`.`empleados_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crud_prueba_tecnica`.`empleados_has_roles` (
  `empleados_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`empleados_id`, `roles_id`),
  INDEX `fk_empleados_has_roles_roles1_idx` (`roles_id` ASC),
  INDEX `fk_empleados_has_roles_empleados1_idx` (`empleados_id` ASC),
  CONSTRAINT `fk_empleados_has_roles_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `crud_prueba_tecnica`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `crud_prueba_tecnica`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
